# config/routes.yaml

# welcome_to_traveler:
#     path:       /
#     controller: App\Controller\TravelerController::index

admin :  
    resource: ../src/Controller/Admin
    name_prefix: admin_
    prefix: /admin
    type: annotation


_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"